obj-$(CONFIG_TOUCHSCREEN_SHTPS_DEV)	+= 	shtps_fts.o				\
										shtps_fts_sub.o			\
										shtps_fts_ldm.o			\
										shtps_fts_devctl.o		\
										shtps_fts_debug.o		\
										shtps_fwctl.o			\
										shtps_filter.o			\
										shtps_i2c.o				\
										shtps_fts_ex_fun.o		\
										fwctl/					\
										focaltech_test/
