obj-y += fih_rere.o
obj-y += fih_apr.o
obj-y += fih_hwid.o
obj-y += fih_info.o
obj-y += fih_emmc.o
obj-y += fih_dram.o
obj-y += fih_e2p.o
obj-y += fih_touch.o
obj-y += fih_lcm.o
obj-y += fih_cpu.o

obj-$(CONFIG_FIH_DEVICE_TREE_DEBUG) += dt_debug/
obj-$(CONFIG_FIH_HALL_SENSOR) += hallsensor/

obj-y += fih_camera_info.o
obj-y += fih_camera_dev.o

obj-$(CONFIG_AWINIC_AW87319) += aw87319/
