/*
 * FocalTech ft8607 TouchScreen driver.
 *
 * Copyright (c) 2016  Focal tech Ltd.
 * Copyright (c) 2016, Sharp. All rights reserved.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef __SHTPS_PARAM_FT8607_H__
#define __SHTPS_PARAM_FT8607_H__

/* ===================================================================================
 * [ Parameters ]
 */
/* -----------------------------------------------------------------------------------
 */
#define SHTPS_REGVAL_STATUS_CRC_ERROR			0xED

/* -----------------------------------------------------------------------------------
 */
SHTPS_PARAM_DEF( SHTPS_PRM_STARTUP_MIN_TIME,	30 );
SHTPS_PARAM_DEF( SHTPS_SLEEP_IN_WAIT_MS, 	30  );
SHTPS_PARAM_DEF( SHTPS_SLEEP_OUT_WAIT_MS, 	0  );
SHTPS_PARAM_DEF( SHTPS_VEILVIEW_PATTERN, 	SHTPS_VEILVIEW_PATTERN_MONOCHROME_1H);

/* -----------------------------------------------------------------------------------
 */
SHTPS_PARAM_DEF(SHTPS_TOUCH_PERFORMANCE_UP_MODE,		1);

/* -----------------------------------------------------------------------------------
 */
#if defined( CONFIG_SHTPS_FOCALTECH_FACETOUCH_DETECT ) || defined( CONFIG_SHTPS_FOCALTECH_FACETOUCH_OFF_DETECT )
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_PALMDET, 			15  );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_FUZZ, 				0   );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MIN, 				1   );
	SHTPS_PARAM_DEF( SHTPS_FINGER_WIDTH_MAX, 				8   );
	SHTPS_PARAM_DEF( SHTPS_LOS_SINGLE, 						0x05);
	SHTPS_PARAM_DEF( SHTPS_LOS_MULTI, 						0x0D);
#else
	#define SHTPS_FINGER_WIDTH_PALMDET (15)
	#define SHTPS_FINGER_WIDTH_MIN     (1)
#endif /* CONFIG_SHTPS_FOCALTECH_FACETOUCH_DETECT || CONFIG_SHTPS_FOCALTECH_FACETOUCH_OFF_DETECT */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_CPU_CLOCK_CONTROL_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_ENABLE_ALLEVENTS, 			1);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_ENABLE_FLICK_DIST, 		15);

	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER0_ENABLE,		 			1);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER0_ENABLE_CORE_NUM, 			4);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER0_CLOCK_FREQUENCY, 			1094400);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER0_ENABLE_TIME_MS, 			100);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER0_ENABLE_TIME_MS_FOR_FLICK,	100);

	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_TOP_CPU_ID, 				4);

	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_ENABLE,		 			1);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_ENABLE_CORE_NUM, 			4);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_CLOCK_FREQUENCY, 			998400);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_ENABLE_TIME_MS, 			100);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_CLUSTER1_ENABLE_TIME_MS_FOR_FLICK, 100);

	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_QOS_LATENCY_ENABLE, 		1);
	SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_QOS_LATENCY_DEF_VALUE, 	189);

	#if defined(SHTPS_DEF_CTRL_CPU_CLOCK_LINKED_LCD_BRIGHT_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_CTRL_CPU_CLOCK_FOR_LOW_BRIGHTNESS_ENABLE,	0);

		#define SHTPS_PERF_LOCK_CLOCK_FREQUENCY_LCD_LPM		960000
	#endif /* SHTPS_DEF_CTRL_CPU_CLOCK_LINKED_LCD_BRIGHT_ENABLE */
	#if defined(SHTPS_DEF_CTRL_CPU_CLOCK_LINKED_ECO_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_CTRL_CPU_CLOCK_FOR_ECO_ENABLE,	0);
	#endif /* SHTPS_DEF_CTRL_CPU_CLOCK_LINKED_ECO_ENABLE */

	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_PERF_LOCK_LOG_ENABLE,	0);
	    #define	SHTPS_PERF_LOCK_PRINT(...)								\
	        if(SHTPS_PERF_LOCK_LOG_ENABLE != 0){						\
	            printk(KERN_DEBUG "[shtps] [perf_lock]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_PERF_LOCK_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_CPU_CLOCK_CONTROL_ENABLE */


/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_LPWG_MODE_ENABLE)
	#if defined( SHTPS_HOST_LPWG_MODE_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_HOST_LPWG_ENABLE, 				0);
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_DIST_THRESHOLD, 		300);
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_CHECK_TIME_MS, 		500);
		SHTPS_PARAM_DEF( SHTPS_HOST_LPWG_HW_REV_CHK_ENABLE, 	0);
	#endif /* SHTPS_HOST_LPWG_MODE_ENABLE */

	#if defined(SHTPS_LPWG_DOUBLE_TAP_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_LPWG_MAXIMUM_TAP_TIME,			0x3C);
		SHTPS_PARAM_DEF( SHTPS_LPWG_MAXIMUM_TAP_DISTANCE,		0x1E);
	#endif /* SHTPS_LPWG_DOUBLE_TAP_ENABLE */

	#if defined(SHTPS_LPWG_CHANGE_SWIPE_DISTANCE_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_LPWG_SWIPE_MINIMUM_DISTANCE, 	0x19);
	#endif /* SHTPS_LPWG_CHANGE_SWIPE_DISTANCE_ENABLE */

	#if defined(SHTPS_LPWG_ALLOWED_SWIPES_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_LPWG_ALLOWED_SWIPES,				0x00);
	#endif /* SHTPS_LPWG_ALLOWED_SWIPES_ENABLE */

	SHTPS_PARAM_DEF( SHTPS_LPWG_ENABLE_GESTURE, 			0x02);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_INTERVAL_DEF, 			0x01);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_INTERVAL, 				0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_WAKEUP_THRESHOLD_DEF, 	0x28);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_WAKEUP_THRESHOLD, 		0x28);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF_DEF, 			0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF, 				0x06);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF_SWEEP_ON, 		0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_HOLDOFF_DOUBLE_TAP,	0x06);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_CTL, 					0x02);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MAX_ACTIVE_DURATION, 		0x01);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MAX_ACTIVE_DURATION_TIME, 	0x05);
	SHTPS_PARAM_DEF( SHTPS_LPWG_REPORT_BEYOND_ACTIVE_AREA, 	0x00);
	SHTPS_PARAM_DEF( SHTPS_LPWG_QOS_LATENCY_DEF_VALUE, 		SHTPS_QOS_LATENCY_DEF_VALUE);
	SHTPS_PARAM_DEF( SHTPS_LPWG_BLOCK_TIME_MAX_MS, 			2000);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MIN_NOTIFY_INTERVAL, 		1000);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MODE_ON_AFTER_SLEEP_ENABLE, 0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_MODE_ON_AFTER_REZERO_ENABLE,0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_DOZE_ENABLE, 				1);
	SHTPS_PARAM_DEF( SHTPS_LPWG_RX_CLIP_AREA_MM,			0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_TX_CLIP_AREA_MM,			3);
	SHTPS_PARAM_DEF( SHTPS_LPWG_CLIP_AREA_X_THRESHOLD,		50);
	SHTPS_PARAM_DEF( SHTPS_LPWG_CLIP_AREA_Y_THRESHOLD,		0);
	SHTPS_PARAM_DEF( SHTPS_LPWG_CLIP_SET_TYPE,				2);

	#if defined(SHTPS_PROXIMITY_SUPPORT_ENABLE)
		#include <sharp/proximity.h>
		SHTPS_PARAM_DEF( SHTPS_LPWG_PROXIMITY_SUPPORT_ENABLE, 	1);
		SHTPS_PARAM_DEF( SHTPS_LPWG_PROXIMITY_CHECK_ASYNC_ENABLE, 0);
		SHTPS_PARAM_DEF( SHTPS_LPWG_MIN_NOTIFY_CANCEL_INTERVAL, 800);
		SHTPS_PARAM_DEF( SHTPS_LPWG_PROXIMITY_CHECK_PREWAIT, 	100);
	#endif /* SHTPS_PROXIMITY_SUPPORT_ENABLE */

	#if defined(SHTPS_LPWG_GRIP_SUPPORT_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_PRM_LPWG_GRIP_OFF_TPS_RESET_ENABLE,	0);
	#endif /* SHTPS_LPWG_GRIP_SUPPORT_ENABLE */
#endif /* SHTPS_LPWG_MODE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_GUARANTEE_I2C_ACCESS_IN_WAKE_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_SUSPEND_I2C_RESUME_FUNC_DELAY, 0);
#endif /* SHTPS_GUARANTEE_I2C_ACCESS_IN_WAKE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_REPORT_TOOL_TYPE_LOCK_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_HOST_EVENT_TOOL_TYPE_LOCK_ENABLE, 		1);
#endif /* SHTPS_REPORT_TOOL_TYPE_LOCK_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_CTRL_FW_REPORT_RATE )
	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_ENABLE, 				1);
	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_PARAM_NORMAL,		0x5C);
	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_PARAM_HIGH,			0x7B);
	#if defined(SHTPS_DEF_CTRL_FW_REPORT_RATE_LINKED_LCD_BRIGHT_ENABLE)
		SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_PARAM_LCD_BRIGHT_LOW, 0x5C);
	#endif /* SHTPS_DEF_CTRL_FW_REPORT_RATE_LINKED_LCD_BRIGHT_ENABLE */

	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_STFLIB_KEVT_NORMAL,			SHTPS_DEF_STFLIB_KEVT_SCANRATE_MODE_NORMAL);
	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_STFLIB_KEVT_HIGH,			SHTPS_DEF_STFLIB_KEVT_SCANRATE_MODE_HIGH);
	SHTPS_PARAM_DEF( SHTPS_CTRL_FW_REPORT_RATE_STFLIB_KEVT_LCD_BRIGHT_LOW,	SHTPS_DEF_STFLIB_KEVT_SCANRATE_MODE_NORMAL);
#endif /* SHTPS_CTRL_FW_REPORT_RATE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_LOW_POWER_MODE_ENABLE )
	SHTPS_PARAM_DEF( SHTPS_LOW_POWER_MODE_CHEK_HW_REV_ENABLE,			0);
	SHTPS_PARAM_DEF( SHTPS_LOW_POWER_MODE_DOZE_ENABLE,					1);
	SHTPS_PARAM_DEF( SHTPS_LOW_POWER_MODE_LCD_BRIGHT_DOZE_ENABLE,		0);
#endif /* SHTPS_LOW_POWER_MODE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined(SHTPS_COVER_ENABLE)
	SHTPS_PARAM_DEF( SHTPS_REG_PRM_COVER_WINDOW_LEFT, 				74);
	SHTPS_PARAM_DEF( SHTPS_REG_PRM_COVER_WINDOW_TOP, 				530);
	SHTPS_PARAM_DEF( SHTPS_REG_PRM_COVER_WINDOW_RIGHT, 				1004);
	SHTPS_PARAM_DEF( SHTPS_REG_PRM_COVER_WINDOW_BOTTOM, 			1319);
#endif /* SHTPS_COVER_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#if defined( SHTPS_DEF_RECORD_LOG_FILE_ENABLE )
	#if defined( SHTPS_LOG_DEBUG_ENABLE )
		SHTPS_PARAM_DEF( SHTPS_RECORD_LOG_FILE_LOG_ENABLE,	0);
	    #define	SHTPS_RECORD_LOG_FILE_PRINT(...)							\
	        if(SHTPS_RECORD_LOG_FILE_LOG_ENABLE != 0){						\
	            printk(KERN_DEBUG "[shtps] [record_log_file]" __VA_ARGS__);	\
	        }
	#else
		#define	SHTPS_RECORD_LOG_FILE_PRINT(...)
	#endif /* SHTPS_LOG_DEBUG_ENABLE */
#endif /* SHTPS_DEF_RECORD_LOG_FILE_ENABLE */

/* -----------------------------------------------------------------------------------
 */
#endif /* __SHTPS_PARAM_FT8607_H__ */
